---
# Variables here are applicable to all host groups NOT roles

# Dummy variable to avoid error because ansible does not recognize the
# file as a good configuration file when no variable in it.
dummy:

###########
# GENERAL #
###########

mon_group_name: mons
osd_group_name: osds
mds_group_name: mdss

# This variable determines if ceph packages can be updated.  If False, the
# package resources will use "state=present".  If True, they will use
# "state=latest".
upgrade_ceph_packages: True

# Enable the ntp service by default to avoid clock skew on
# ceph nodes
ntp_service_enabled: true

##########
# STABLE #
##########

ceph_origin: 'upstream'
ceph_stable: true
ceph_stable_release: 'jewel'

######################
# CEPH CONFIGURATION #
######################

## Ceph options
cephx: true

## Monitor options
monitor_interface: eth0
mon_use_fqdn: false # if set to true, the MON name used will be the fqdn in the ceph.conf

## OSD options
journal_size: 5120 # OSD journal size in MB
public_network: "10.101.0.0/24"
cluster_network: "10.101.0.0/24"
osd_mkfs_type: xfs
osd_mkfs_options_xfs: -f -i size=2048
osd_mount_options_xfs: noatime,largeio,inode64,swalloc
osd_objectstore: filestore

###################
# CONFIG OVERRIDE #
###################

# Ceph configuration file override.
# This allows you to specify more configuration options
# using an INI style format.
# The following sections are supported: [global], [mon], [osd], [mds], [rgw]
#
ceph_conf_overrides:
  global:
    osd_pool_default_pg_num: 324
    osd_pool_default_size: 3
